replicaCount: 3

imagePullSecrets:
  - name: nexus-registry

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - general
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: app
        topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: app

image:
  repository: "51.178.52.51:8019/sample-app"
  tag: "latest"
  pullPolicy: Always

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingressRoute:
  host: app.kubequest.local

env:
  DB_CONNECTION: mysql
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "myapp"
  DB_USERNAME: "myuser"
  DB_PASSWORD: "mypassword"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 2
