on:
  pull_request:

jobs:
  lint:
    name: 🧪 Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0
      - name: Lint all charts
        run: |
          helm lint sample-app-master/helm/app --strict

  docker:
    name: 🐳 Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."51.178.52.51:8019"]
              http = true
              insecure = true

      - name: Login to Nexus Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 51.178.52.51:8019 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 \
            -t 51.178.52.51:8019/sample-app:latest \
            sample-app-master/ --push